In [2]:
import pandas as pd
import numpy as np
import scipy.stats
import seaborn as sns
import matplotlib.pyplot as plt
import gseapy as gp
from gseapy.plot import barplot, dotplot

import cptac
import cptac.utils as u

In [3]:
b = cptac.Gbm()

In [23]:
r = b.get_proteomics()
l = r.apply(lambda x: x > .01)
l

Name,A1BG,A2M,AAAS,AACS,AADAT,AAED1,AAGAB,AAK1,AAMDC,AAMP,...,ZSCAN31,ZSWIM8,ZW10,ZWILCH,ZWINT,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
Sample_ID,,,,,,,,,,,,,,,,,,,,,
S001,True,True,False,False,True,False,False,False,False,True,...,False,False,False,False,False,True,True,False,False,True
S002,False,True,True,False,False,True,True,False,True,False,...,False,True,False,True,False,True,True,True,False,True
S003,True,True,False,False,True,True,False,True,False,False,...,False,False,False,True,False,True,False,True,False,False
S004,False,True,True,False,True,False,True,True,False,False,...,False,False,True,True,True,False,True,False,False,False
S005,False,False,False,False,True,False,False,True,False,True,...,False,False,True,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S111,False,False,False,True,True,False,True,True,False,True,...,False,True,False,False,True,False,True,False,True,False
S112,False,False,False,True,False,False,False,True,False,True,...,False,True,False,False,False,False,True,False,True,False
S113,False,False,False,True,False,True,False,True,False,True,...,False,True,False,False,False,True,True,False,True,False
S114,False,False,False,True,True,False,True,True,False,True,...,True,True,False,False,False,False,True,False,True,False
S115,False,False,False,True,True,False,True,True,False,True,...,False,True,False,False,True,False,True,False,True,False

In [24]:
l = l.reset_index()
l

Name,Sample_ID,A1BG,A2M,AAAS,AACS,AADAT,AAED1,AAGAB,AAK1,AAMDC,...,ZSCAN31,ZSWIM8,ZW10,ZWILCH,ZWINT,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
0,S001,True,True,False,False,True,False,False,False,False,...,False,False,False,False,False,True,True,False,False,True
1,S002,False,True,True,False,False,True,True,False,True,...,False,True,False,True,False,True,True,True,False,True
2,S003,True,True,False,False,True,True,False,True,False,...,False,False,False,True,False,True,False,True,False,False
3,S004,False,True,True,False,True,False,True,True,False,...,False,False,True,True,True,False,True,False,False,False
4,S005,False,False,False,False,True,False,False,True,False,...,False,False,True,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,S111,False,False,False,True,True,False,True,True,False,...,False,True,False,False,True,False,True,False,True,False
105,S112,False,False,False,True,False,False,False,True,False,...,False,True,False,False,False,False,True,False,True,False
106,S113,False,False,False,True,False,True,False,True,False,...,False,True,False,False,False,True,True,False,True,False
107,S114,False,False,False,True,True,False,True,True,False,...,True,True,False,False,False,False,True,False,True,False
108,S115,False,False,False,True,True,False,True,True,False,...,False,True,False,False,True,False,True,False,True,False

In [28]:
#li = list(l.columns)
li = ['A1BG']
#r = l.groupby(by =li, axis = 1)

In [47]:
omics_and_mutations = b.join_omics_to_mutations(
        mutations_genes = 'TP53', omics_df_name = 'CNV', omics_genes = 'TP53')
tumors = omics_and_mutations.Sample_Status
cnv = b.get_CNV()
cnv

Warning: In joining the somatic_mutation table, no mutations were found for the following samples, so they were filled with Wildtype_Tumor or Wildtype_Normal: 67 samples for the TP53 gene (C:\Users\brittany henderson\Anaconda3\envs\Research\lib\site-packages\ipykernel_launcher.py, line 2)
Warning: CNV data was not found for the following samples, so CNV data columns were filled with NaN for these samples: S020 (C:\Users\brittany henderson\Anaconda3\envs\Research\lib\site-packages\ipykernel_launcher.py, line 2)

Name,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
Sample_ID,,,,,,,,,,,,,,,,,,,,,
S001,-0.628254,-0.724469,0.044307,0.044307,-0.021595,0.048478,0.046797,0.044307,0.044307,0.046797,...,0.067722,-0.719102,-0.724469,0.025915,0.025915,0.046797,-0.021595,-0.021595,0.045061,-0.584579
S002,0.304944,-0.658366,-0.086667,-0.086667,0.174725,0.037394,0.155344,-0.086667,-0.086667,0.155344,...,-0.162332,-0.147051,-0.658366,0.101335,0.101335,0.155344,0.174725,0.174725,0.384346,0.065126
S003,0.247958,-0.341251,-0.013136,-0.013136,-0.010699,-0.007682,-0.009031,-0.011275,-0.011275,-0.009031,...,-0.013009,-0.009965,-0.341251,-0.000809,-0.000809,-0.009031,-0.010699,-0.010699,0.267624,-0.004149
S004,0.271067,-0.692011,0.005182,0.005182,-0.018290,-0.715434,0.014659,-0.185699,-0.185699,0.014659,...,0.423260,-0.013910,-0.692011,-0.048670,-0.048670,0.014659,-0.018290,-0.018290,0.458499,-0.031579
S005,0.351638,-0.542862,-0.018968,-0.018968,-0.021372,-0.539923,-0.026650,-0.018968,-0.014971,-0.026650,...,-0.046543,-0.018644,-0.542862,-0.022360,-0.022360,-0.026650,-0.019001,-0.019001,0.360617,-0.015862
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S100,0.046015,-0.608561,0.047384,0.047384,0.045932,-0.615535,0.044781,0.047384,0.045924,0.044781,...,0.042857,0.028227,-0.608561,0.038111,0.038111,0.044781,0.045932,0.045932,0.495176,0.043384
S101,0.474547,-0.826221,-0.027430,-0.027430,-0.020040,-0.020828,-0.024531,-0.027430,-0.027430,-0.024531,...,-0.024348,-0.023087,-0.826221,-0.050382,-0.050382,-0.024531,-0.020040,-0.020040,0.479522,-0.013726
S102,0.285339,-0.402990,-0.014681,-0.014681,-0.015028,-0.037330,-0.011292,-0.017763,-0.017763,-0.011292,...,-0.018322,-0.012473,-0.402990,-0.030983,-0.030983,-0.011292,-0.012487,-0.012487,0.291200,-0.012891
S104,0.525859,-0.144158,0.051230,0.051230,-0.123914,-0.639521,-0.124906,0.055155,0.041186,-0.124906,...,-0.135363,-0.130918,-0.144158,0.507865,0.507865,-0.124906,-0.128452,-0.128452,0.218415,-0.623024
S105,0.056233,-0.208898,-0.663427,-0.663427,0.089764,0.088281,0.083330,-0.660318,0.076746,0.083330,...,0.084255,0.094754,-0.208898,0.058731,0.058731,0.083330,0.089764,0.089764,0.095345,0.095364

In [40]:
for e in li:
    print(e)
    y = l[e]
    #print(y)
    print(y.value_counts())

A1BG
False    57
True     52
Name: A1BG, dtype: int64

KeyError: True

In [26]:
gene = 'RB1'
mut = b.get_somatic_mutation()
rb1 = mut.loc[mut['Gene'] == 'RB1']
rb1

Name      Gene           Mutation       Location
Sample_ID
S001       RB1        Splice_Site  p.X654_splice
S002       RB1    Frame_Shift_Del    p.F117Lfs*8
S004       RB1      Splice_Region        p.D349=
S004       RB1        Splice_Site  p.X605_splice
S014       RB1        Splice_Site  p.X500_splice
S041       RB1        Splice_Site  p.X500_splice
S061       RB1    Frame_Shift_Ins   p.N290Kfs*20
S068       RB1  Nonsense_Mutation        p.R358*
S092       RB1  Nonsense_Mutation        p.R552*
S094       RB1    Frame_Shift_Del    p.N505Sfs*2
S099       RB1    Frame_Shift_Del   p.I680Sfs*16

In [33]:
# changes in phosphosites
phos = b.get_phosphoproteomics()
phosdf = b.reduce_multiindex(phos, flatten = True)
phosdf

Name,A2M_S273_KYS*DASDCHGEDSQAFCEK_NP_000005.2,AAAS_S495_FS*PVLGR_NP_056480.1,AAAS_S495_IAHIPLYFVNAQFPRFS*PVLGR_NP_056480.1,AAAS_S525_AQEPPAGGGGSIHDLPLFTETSPTS*APWDPLPGPPPVLPHSPHSHL_NP_056480.1,AAAS_S525S541_AQEPPAGGGGSIHDLPLFTETSPTS*APWDPLPGPPPVLPHS*PHSHL_NP_056480.1,AAAS_S541_AQEPPAGGGGSIHDLPLFTETSPTSAPWDPLPGPPPVLPHS*PHSHL_NP_056480.1,AAED1_S12_QVS*GAAALVPAPSGPDSGQPLAAAVAELPVLDAR_NP_714542.1,AAGAB_S189_NQGFSLLNS*LTGTNHSIGSADPCHPEQPHLPAADSTESLSDHR_NP_078942.3,AAGAB_S196S199_NQGFSLLNSLTGTNHS*IGS*ADPCHPEQPHLPAADSTESLSDHR_NP_078942.3,AAGAB_S199_NQGFSLLNSLTGTNHSIGS*ADPCHPEQPHLPAADSTESLSDHR_NP_078942.3,...,ZZZ3_S396Y399_NS*SPY*RENGQFEENNLSPNETNATVSDNVSQSPTNPGEISQNEK_NP_056349.1,ZZZ3_S397_NSS*PYRENGQFEENNLSPNETNATVSDNVSQSPTNPGEISQNEK_NP_056349.1,ZZZ3_S397S420_NSS*PYRENGQFEENNLSPNETNATVS*DNVSQSPTNPGEISQNEK_NP_056349.1,ZZZ3_S397S426_NSS*PYRENGQFEENNLSPNETNATVSDNVSQS*PTNPGEISQNEK_NP_056349.1,ZZZ3_S397Y399_NSS*PY*RENGQFEENNLSPNETNATVSDNVSQSPTNPGEISQNEK_NP_056349.1,ZZZ3_S606_S*PLDPKK_NP_056349.1,ZZZ3_S777_SCFHSHMNTAVEDAS*DDESIPIMYR_NP_056349.1,ZZZ3_T418_NSSPYRENGQFEENNLSPNETNAT*VSDNVSQSPTNPGEISQNEK_NP_056349.1,ZZZ3_Y399_NSSPY*RENGQFEENNLSPNETNATVSDNVSQSPTNPGEISQNEK_NP_056349.1,ZZZ3_Y399S426_NSSPY*RENGQFEENNLSPNETNATVSDNVSQS*PTNPGEISQNEK_NP_056349.1
Sample_ID,,,,,,,,,,,,,,,,,,,,,
S001,NaN,0.053418,NaN,0.118623,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S002,NaN,-0.093105,-0.095450,0.069499,NaN,NaN,-1.221096,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S003,NaN,-1.084975,NaN,NaN,NaN,1.368630,NaN,NaN,NaN,NaN,...,NaN,-1.037834,NaN,NaN,NaN,0.064722,0.216607,NaN,NaN,NaN
S004,NaN,-0.260149,0.390607,0.336969,NaN,0.411596,NaN,0.812857,0.118422,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S005,NaN,-0.344549,NaN,-0.082962,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S111,NaN,-0.657678,1.260854,NaN,0.16353,0.311555,0.200849,NaN,0.216371,NaN,...,NaN,-0.511102,NaN,-0.364957,NaN,NaN,NaN,NaN,NaN,0.018092
S112,NaN,-0.651907,0.607397,NaN,NaN,-0.379264,NaN,NaN,NaN,NaN,...,NaN,-1.138928,NaN,NaN,-0.523611,NaN,NaN,NaN,NaN,NaN
S113,NaN,-0.105979,0.694516,0.326843,NaN,NaN,0.446820,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S114,NaN,-0.542320,0.016551,NaN,NaN,-0.438673,NaN,NaN,NaN,NaN,...,-0.479712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S115,NaN,-0.142143,0.029264,NaN,NaN,NaN,-0.972054,NaN,NaN,NaN,...,NaN,-0.374362,NaN,NaN,NaN,-0.270359,NaN,NaN,NaN,NaN

In [10]:
pdf = b.join_omics_to_mutations(mutations_genes=[gene], omics_df_name="proteomics", omics_genes=[gene], mutations_filter = ['Missense_Mutation'])

Warning: Filter value Missense_Mutation does not exist in the mutations data for the RB1 gene, though it exists for other genes. (C:\Users\brittany henderson\Anaconda3\envs\Research\lib\site-packages\ipykernel_launcher.py, line 1)
Warning: In joining the somatic_mutation table, no mutations were found for the following samples, so they were filled with Wildtype_Tumor or Wildtype_Normal: 99 samples for the RB1 gene (C:\Users\brittany henderson\Anaconda3\envs\Research\lib\site-packages\ipykernel_launcher.py, line 1)

In [8]:
pdf

Name,RB1_proteomics,RB1_Mutation,RB1_Location,RB1_Mutation_Status,Sample_Status
Sample_ID,,,,,
S001,-1.799180,[Splice_Site],[p.X654_splice],Single_mutation,Tumor
S002,-1.071307,[Frame_Shift_Del],[p.F117Lfs*8],Single_mutation,Tumor
S003,0.154265,[Wildtype_Tumor],[No_mutation],Wildtype_Tumor,Tumor
S004,-0.884636,"[Splice_Region, Splice_Site]","[p.D349=, p.X605_splice]",Multiple_mutation,Tumor
S005,0.041888,[Wildtype_Tumor],[No_mutation],Wildtype_Tumor,Tumor
...,...,...,...,...,...
S111,-0.625293,[Wildtype_Normal],[No_mutation],Wildtype_Normal,Normal
S112,-0.522348,[Wildtype_Normal],[No_mutation],Wildtype_Normal,Normal
S113,-0.901327,[Wildtype_Normal],[No_mutation],Wildtype_Normal,Normal
S114,-0.546379,[Wildtype_Normal],[No_mutation],Wildtype_Normal,Normal
S115,-0.842556,[Wildtype_Normal],[No_mutation],Wildtype_Normal,Normal